# Generated by Django 5.1.6 on 2025-02-16 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('internship', 'Internship')], max_length=50)),
                ('job_location', models.CharField(choices=[('onsite', 'On-Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiter')),
            ],
            options={
                'db_table': 'job_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
