# Generated by Django 5.1.4 on 2025-01-29 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0002_remove_recruiter_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=50)),
                ('job_location', models.CharField(choices=[('On-Site', 'On-Site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiter')),
            ],
            options={
                'db_table': 'job_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
