# Generated by Django 5.1.4 on 2025-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='description',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_location',
            field=models.CharField(choices=[('onsite', 'On-Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('internship', 'Internship')], max_length=50),
        ),
    ]
