# Generated by Django 5.1.4 on 2025-01-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
