# Generated by Django 5.1.4 on 2025-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
