# Generated by Django 5.1.4 on 2025-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_developer_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='email_verification_token',
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'verification_tokens',
                'indexes': [models.Index(fields=['email'], name='verificatio_email_bf2b5c_idx'), models.Index(fields=['token'], name='verificatio_token_c488e1_idx')],
            },
        ),
    ]
