# Generated by Django 5.1.4 on 2025-01-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_remove_developer_email_verification_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
