# Generated by Django 5.1.4 on 2025-01-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_delete_verificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='email_verified',
        ),
    ]
