# Generated by Django 5.1.4 on 2025-01-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='email_verified',
        ),
    ]
